# Generated by Django 4.2.6 on 2023-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='date',
            field=models.DateField(),
        ),
    ]
