# Generated by Django 4.2.6 on 2023-12-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_programjudgeallocation_programeshedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programenrollment',
            name='PROGRAMME',
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='PROGRAMMESCHEDULE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.programschedule'),
            preserve_default=False,
        ),
    ]
