# Generated by Django 4.2.6 on 2024-01-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_programenrollment_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='candidateresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=10)),
                ('CANDIDATE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.candidate')),
                ('JUDGE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.judge')),
                ('PROGRAMME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
    ]
