# Generated by Django 4.2.6 on 2024-01-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_rename_groups_award_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='position',
        ),
    ]
