# Generated by Django 4.2.6 on 2023-12-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('hname', models.CharField(max_length=100)),
                ('proffession', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programname', models.CharField(max_length=100)),
                ('programtype', models.CharField(max_length=100)),
                ('groupprogram', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rulesandregulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(max_length=100)),
                ('PROGRAMME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='programschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('fromtime', models.CharField(max_length=100)),
                ('totime', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('PROGRAM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='programjudgeallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JUDGE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.judge')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login')),
                ('PROGRAMME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='programenrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.candidate')),
                ('PROGRAMME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login'),
        ),
        migrations.CreateModel(
            name='groupleaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('GROUP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.groups')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(default='0', max_length=100)),
                ('LOGIN', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('type', models.CharField(default='0', max_length=100)),
                ('LOGIN', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='GROUP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.groups'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='PROGRAM',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.program'),
        ),
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardtype', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('CANDIDATE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.candidate')),
                ('PROGRAMME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.program')),
            ],
        ),
    ]
