# Generated by Django 4.2.6 on 2023-12-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_programschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programjudgeallocation',
            name='PROGRAMESHEDULE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.programschedule'),
        ),
    ]
