# Generated by Django 4.2.6 on 2024-01-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_feedback_date_candidateresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='year',
            new_name='grade',
        ),
    ]
