# Generated by Django 4.2.6 on 2024-01-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_rename_year_award_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='awardtype',
            new_name='chessnumber',
        ),
        migrations.RemoveField(
            model_name='award',
            name='PROGRAMME',
        ),
        migrations.AddField(
            model_name='award',
            name='groups',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.groups'),
        ),
        migrations.AddField(
            model_name='award',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
