# Generated by Django 4.2.6 on 2024-02-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_remove_award_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('GROUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.groups')),
            ],
        ),
    ]
